name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: deploy new code
      uses: JimCronqvist/action-ssh@master
      with: 
        hosts: ${{secrets.SSH_HOST}}
        privateKey: ${{secrets.SSH_PRIVATE_KEY}}
        debug: false
        command:
          ls -lah && /
          echo "Hello World!"